# Generated by Django 2.2.6 on 2019-12-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(default='', max_length=480),
        ),
    ]
