# Generated by Django 2.2.6 on 2019-12-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_uses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uses',
            new_name='Use',
        ),
    ]
