# Generated by Django 2.2.6 on 2019-12-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191217_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='pollinators',
            field=models.ManyToManyField(to='main_app.Pollinator'),
        ),
    ]
