# Generated by Django 2.2.6 on 2019-12-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191217_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollinator',
            name='isInsect',
            field=models.BooleanField(default=True),
        ),
    ]
